### ISSUE TITLE
doc/safegcd_implementation: clarifications

### ISSUE THREAD

**Issue by TuomLarsen** [bitcoin-core/secp256k1#1077]
Thank you for writing up the explanation on safegcd, very useful! However, could you please clarify a few points?

* The body of the very first `gcd` function in Section 1 seems to be the function `divsteps2` from Figure 10.1 of the original paper but without all of the `truncate` calls. What are the consequences of omitting the calls? Aren't `f`, `g` going to be too large case then?
* In the function `modinv` first introduced in Section 3, there is `f % 2**N`, `g % 2**N`. In Python `%` operator always returns non-negative result, even for negative arguments. Doesn't this throw `delta` out of sync with `f`, `g`?
* If that's not too much to ask, could you please explain how a variable time and recursive version of `modinv_var` would look like, akin to `jumpdivsteps2` found in Figure 10.2?

Thank you very much in advance! I hope posting here is not too off-topic, I didn't know how else to reach the authors of the document.

**Comment by peterdettman** [comment]
I guess the main point to make is that our implementation does not use the recursive structure of the general safegcd algorithm (because we are targeting only a fixed relatively-small field).

> * The body of the very first `gcd` function in Section 1 seems to be the function `divsteps2` from Figure 10.1 of the original paper but without all of the `truncate` calls. What are the consequences of omitting the calls? Aren't `f`, `g` going to be too large case then?

IMO, the gcd in Section 1 of the doc has more to do with shortgcd2 from Figure 1.2 of the paper, except using a (non-const-time) termination condition on g instead of a fixed number of iterations.

> * In the function `modinv` first introduced in Section 3, there is `f % 2**N`, `g % 2**N`. In Python `%` operator always returns non-negative result, even for negative arguments. Doesn't this throw `delta` out of sync with `f`, `g`?

No. divsteps only operate on low bits of f/g without regard to the sign of the full value. Also delta is not tracking signs of f/g but rather the balance between how many times we've zeroed the LSB of f vs that of g. When we have a choice as to which of f/g to zero the LSB of next (i.e. when both f,g are odd), then we choose the one that has had the fewest zeroed so far, which is tracked by delta.

> * If that's not too much to ask, could you please explain how a variable time and recursive version of `modinv_var` would look like, akin to `jumpdivsteps2` found in Figure 10.2?

Yeah, it's a bit much because we didn't actually do that. However regarding a var-time jumpdivsteps2, a general observation would be that once the low t bits of g are all 0, then the whole effect of divsteps2 (or the remaining iterations) is only to increase delta by 1 per iteration. That should also be true of jumpdivsteps2. So I would guess that you could test for g == 0 mod 2^t at the top of jumpdivsteps2, to then just return delta+t,f,g.

**Comment by TuomLarsen** [comment]
Thank you very much for the reply! I'm closing it, then.
