### ISSUE TITLE
Bitcoin Core `configure` fails after #1084 was merged

### ISSUE THREAD

**Issue by dhruv** [bitcoin-core/secp256k1#1127]
Bitcoin Core's secp subtree is currently at `44c2452fd387f7ca604ab42d73746e7d3a44d8a2`. Updating the subtree to `cd470333351bd6d90296352f2a957f38bbdaf014` (merging #1084) causes Bitcoin Core CI failure as it cannot run the config scripts anymore as seen [here](https://github.com/dhruv/bitcoin-core-ci/pull/14/checks)

I don't know much about build systems, but am happy to learn and help with guidance.

**Comment by real-or-random** [comment]
Hmmm.... So apparently Core's CI sets some explicit some cache file that caches some configuration values:
https://cirrus-ci.com/task/6310546097045504?logs=ci#L478-L485

I have never really used explicit cache files, but the error message tells us that the file is outdated. So I believe this is not an issue in our repo. Let me ask the Core build system experts on IRC.

**Comment by real-or-random** [comment]
> Hmmm.... So apparently Core's CI sets some explicit cache file that caches some configuration values:

Hm no, so this done automatically by autoconf when running `AC_CONFIG_SUBDIRS`. And IIUC then it complains that the environment has changed in between the two configure runs (core and secp256k1), namely
```
configure: error: `PKG_CONFIG_PATH' was not set in the previous run
```

@dhruv Can you test https://github.com/bitcoin-core/secp256k1/pull/1090? I suspect that to be the issue instead of #1084 but  I could be wrong.

**Comment by real-or-random** [comment]
Okay, so I believe this is the reason:

https://github.com/bitcoin/bitcoin/blob/948f5ba6363fcc64f95fed3f04dbda3d50d61827/depends/config.site.in#L87-L93

These were added in the same PR as this commit which implemented the unexport.
https://github.com/bitcoin/bitcoin/pull/5220/commits/0dc8613864052172447d32338f4492669918cefa
But the code added by this commit was removed apparently, probably because it "just worked" as long as secp256k1 also used pkgconf... (can't find the commit right now...) I believe it should be brought back...  


"sigh", indeed.


cc @theuni

**Comment by real-or-random** [comment]
This is the bad commit:
https://github.com/bitcoin/bitcoin/pull/24792/commits/ee30bf7c01922938bcf861a57cdf2249edb36256

@dhruv Can you try if CI passes if you revert this? (I guess a local depends build will do the job too, if this is easier than running CI).

**Comment by real-or-random** [comment]
> edit: ok, sorry, this would work. But since only secp256k1 was using this stuff, the proper fix is just to remove those lines here entirely: [bitcoin/bitcoin@`948f5ba`/depends/config.site.in#L85-L94](https://github.com/bitcoin/bitcoin/blob/948f5ba6363fcc64f95fed3f04dbda3d50d61827/depends/config.site.in#L85-L94)

https://github.com/bitcoin/bitcoin/pull/25655 taught me I'm wrong, so I believe the right fix is to revert https://github.com/bitcoin/bitcoin/commit/ee30bf7c01922938bcf861a57cdf2249edb36256. @dhruv Could you try if this makes the subtree update work?

**Comment by dhruv** [comment]
Verified that this works now: https://github.com/dhruv/bitcoin-core-ci/pull/14/checks

Thanks, @real-or-random !
