### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by jonasnick** [bitcoin-core/secp256k1#1220]
Looking at the [PRs since the last release](https://github.com/bitcoin-core/secp256k1/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E%3D2022-12-12+base%3Amaster+sort%3Aupdated-asc), the following ones seem to deserve a changelog entry:

- https://github.com/bitcoin-core/secp256k1/pull/1178
- https://github.com/bitcoin-core/secp256k1/pull/1209
- maybe https://github.com/bitcoin-core/secp256k1/pull/1212

**Comment by real-or-random** [comment]
Thanks, I was also about to make a list. What are your thoughts on adding https://github.com/bitcoin-core/secp256k1/pull/1188? This can be interesting for users who run the tests manually instead of using `make check`. I guess there are a few reasons to do this.


>     * maybe [Prevent dead-store elimination when clearing secrets in examples #1212](https://github.com/bitcoin-core/secp256k1/pull/1212)

I don't think it's strictly necessary, but I'm happy to include it. It won't hurt to draw the attention of users to this.
