### ISSUE TITLE
autotools: `make precomp` does not work for out-of-source builds

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/secp256k1#1280]
On master (4258c54f4ebfc09390168e8a43306c46b315134b):
```
$ ./autogen.sh
$ mkdir ../build && cd ../build
$ ../secp256k1/configure
$ make precomp
make: Nothing to be done for 'precomp'.
$ make clean-precomp
rm -f src/precomputed_ecmult_gen.c src/precomputed_ecmult.c
$ make precomp
make: Nothing to be done for 'precomp'.
```

**Comment by real-or-random** [comment]
Well, I think that's somewhat by design. 

The problem here is not that `make precomp` does not work. The problem is that `make clean-precomp` has nothing to clean: `src/precomputed_ecmult_gen.c src/precomputed_ecmult.c` simply don't exist in the build dir.

So, what is `make clean-precomp` supposed to do in an out-of-tree build? We have three options:
 1. Do nothing. Disadvantage: It doesn't work.
 2. Error out. Disadvantage: It doesn't work either.
 3. Clean in the src dir. Disadvantage: That violates the convention that an out-of-tree build should not touch the source dir.

As I see it, the maintainer features generate source files, so it's natural that they only work in the source dir.

Having said that, it would probably be okay to implement 3. But I'm not convinced that this is much better. The build should work then somewhat because the precomp files are then generated in the *build dir* (since we have https://github.com/bitcoin-core/secp256k1/pull/1160/commits/e862c4af0c5a7300129700d38eff499a836a108d0). But this also means that another `make clean-precomp` will (try to) delete the files in the source dir again.

I lean towards accepting that this is a maintainer-only feature and works only in the source dir. That will translate to option 2.

Here's an entirely different idea:
With all this autotools mess, and since we don't even have these features in CMake, it would perhaps be cleaner to move (maintainer-)generation of the distributed files entirely out of the build system(s). This is currently hard since creating the files involves running a C program, which needs to be compiled, which needs some kind of build infrastructure. If we used Python to create the table files (see https://github.com/bitcoin-core/secp256k1/pull/919), this would simplify some things. In particular because we have a "maintainer dependency" on Python anyway now with the test vector scripts.... On the other hand, all of this is work and I doubt it's worth spending our time on this right now. (This is true in general when it comes to solving this "issue" here).

**Comment by hebasto** [comment]
Thanks for clarification!
