### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by alexreg** [bitcoin-core/secp256k1#396]
Is there any reason that no versions have been tagged or actual releases made for this library, yet?

**Comment by afk11** [comment]
Largely because the API changed so frequently! That hasn't happened for a year or so now, so I'm starting to get curious as well.

**Comment by alexreg** [comment]
Yes, that’s been my thoughts too. I believe the API has been pretty stable recently, so it would be nice to have a proper release, like a 0.1.0 at least.

**Comment by apoelstra** [comment]
The plan is not to have any versions until the symbolic "1.0" release, after which we stop breaking stuff all the time (and use semantic versioning so that any breaks that *do* happen won't wreck people's stuff).

There are still a few tasks pending before 1.0 -- on my plate, getting the low-order-curve exhaustive tests complete and merged. But also more serious things like finalizing the Schnorr signature API.

We had planned to have this done a while ago, but all of the primary developers on this project have been extremely busy for the last several months.

**Comment by gmaxwell** [comment]
Actually documenting and publishing on many of the (potentially risky) novel optimization we use is something I consider a requirement before considering a published version here.

**Comment by alexreg** [comment]
Thanks for clarifying, @apoelstra. I look forward to the day it is standardised! I didn't realise quite how original some of this library's implementation was.

**Comment by chfast** [comment]
Can you create a milestone to track this list of pending tasks?

**Comment by afk11** [comment]
@gmaxwell any updates on publishing yet? Really wondering when this issue will be closed, this one is related also: https://github.com/bitcoin-core/secp256k1/issues/286

**Comment by sipa** [comment]
Closing in favor of #286.
