### ISSUE TITLE
Verify failing with particular Tx

### ISSUE THREAD

**Issue by jamescarter-le** [bitcoin-core/secp256k1#419]
I have verified the full Testnet chain up to block 929166, working on block 929167 there is this transaction which does not verify through my software: https://api.blockcypher.com/v1/btc/test3/txs/23202c2534be0567d4b339142f8a9a53545123eb61f61717fdedbef8effc53e0?limit=50&includeHex=true

It is a P2SH, with the following details:
scriptSig: <02A14A78351C4B47F3099120D4565A8E7E6DFBDA1E4B570DFC573A9B2894038D11> <093006020101020101017CAC>
redeemScript: <300602010102010101> OP_SWAP OP_CHECKSIG

The signature gives R and S values of 1?

These are steps the process goes through:

<300602010102010101>
<02A14A78351C4B47F3099120D4565A8E7E6DFBDA1E4B570DFC573A9B2894038D11>

OP_SWAP

<02A14A78351C4B47F3099120D4565A8E7E6DFBDA1E4B570DFC573A9B2894038D11>
<300602010102010101>

Public Key: <02A14A78351C4B47F3099120D4565A8E7E6DFBDA1E4B570DFC573A9B2894038D11>
Signature: <300602010102010101>

TxHashType: 01
Public Key: <02A14A78351C4B47F3099120D4565A8E7E6DFBDA1E4B570DFC573A9B2894038D11>
Signature: <3006020101020101>
VerifyHash: 355ED31E8E528CCA2F19DC4A0BEAD610CF750CDE1065D17B508AE04073E9FA3F

OP_CHECKSIG = FAIL

I know this has been verified through the library because my reference Bitcoin Core (v0.13.0) client passed this transaction to me.

I do not understand how this transaction can be verified with the signature that has been passed in.

I would appreciate any help.

**Comment by apoelstra** [comment]
I can verify (with Sage) that the signature you've given does not validate with the hash you've given. At first glance it looks like you've extracted the data correctly so I assume the hash is wrong. My guess is something to do with Core's search-and-replace code that removes the signature from the data that gets hashed -- though I had thought all the known tricks around this had been exploited long ago on testnet, so I'm surprised to see something new.

As to "how can a 1,1 signature validate", the answer is that this transaction was designed to require pubkey recovery to spend: the public key provided in the scriptSig is not one that anybody knows a secret key to, but was computed from the (1,1) signature and the signature hash.

Closing this issue since the secp bugtracker is not a help channel -- for more information please ask about this on IRC. You can find me as @andytoshi on many Bitcoin-related channels.
