### ISSUE TITLE
Second generator?

### ISSUE THREAD

**Issue by foomatic29** [bitcoin-core/secp256k1#482]
Is there support (or planned support) for a second curve generator in this library, for Pedersen commitments and the like...

**Comment by apoelstra** [comment]
There is a second generator in [secp256k1-zkp](https://github.com/elementsproject/secp256k1-zkp) which is our fork of libsecp with support for Pedersen commitments, rangeproofs, etc. Because this library is a supporting library for Bitcoin, which currently does not use Pedersen commitments anywhere, it doesn't contain the extra modules which would make use of this generator.

If you have a Bitcoin-relevant use case for Pedersen commitments I think a case could be made to bring this support into libsecp, but I'm not aware of one.
