### ISSUE TITLE
Directly expose privatekey inverse function

### ISSUE THREAD

**Issue by madeken** [bitcoin-core/secp256k1#582]
secp256k1.h doesn't include any functionality to get an inverse of a private key.

I see another project doing it a bit manually after including scalar_impl.h

https://github.com/cryptocoinjs/secp256k1-node/blob/e9d38b279a25049a5f4f66f73f06fb2d70868ce6/src/privatekey.cc#L78-L101

I'm wonder if it would be a bit more appropriate to expose a privkey_inverse function a bit more directly in secp256k1.h?

Thanks!

**Comment by real-or-random** [comment]
Not doing this is mentioned in the README as an explicit goal: 
> Expose only higher level interfaces to minimize the API surface and improve application security. ("Be difficult to use insecurely.")

**Comment by apoelstra** [comment]
What is the usecase for this? As Tim says, we don't wan't to expose low-level mathematical operations which would represent an ongoing support burden (and are almost certainly going to be used, eventually, in confused and inefficient and insecure ways). But if there is high-level functionality missing we could certainly consider that.

**Comment by madeken** [comment]
Understood. You guys are right. However, I wonder if it applies here. While computing the inverse of a privatekey is a low-level operation, I suspect it's only done in contexts in which it's a required operation that would be implemented anyway (i.e. it's not subverting otherwise high-level functionality).

I notice it's also implemented by quite a few EC libraries and bindings as well, so I suspect if this library exposes it, it'll only be less likely to implemented badly. 

In my case, it's a required operation of a blinded signature scheme I am working with. I don't really have the luxury of avoiding it, it's just a question of if I can use libsecp256k1 already efficient implementation or my own slow crappy version. 

Also is it much different than something like `secp256k1_ec_privkey_negate` ?

**Comment by apoelstra** [comment]
`privkey_negate` also leaves a bad taste in my mouth, but it's purpose (to turn the `tweak_add` functions into `tweak_sub`) is algebraically inconsequential... and it take negligible time to run.

**Comment by gmaxwell** [comment]
If we were compiled without ECDSA verification I believe we would have no use for a scalar negate in the library at all.

Probably your "blinded signature scheme" is insecure.  I'd actually take a sizable bet because essentially every description I've seen of ECC blind signing I've seen online was insecure as described (and also failed to even mention the risks).

If getting access to some libsecp256k1 internal is getting in your way, then you probably have a more serious problem you're not even aware of...  this is part of the reason for our motivation in not offering a grabbag of low level primitives.  If you'd like to implement blind signing against the schnorr PRs in the repo, I'd be happy to review them.

**Comment by apoelstra** [comment]
The correct way to implement this is to fork the library, add a module which implements a safe interface to a complete cryptosystem, and perhaps PR that here (or to secp256k1-zkp which is more accepting of experimental things).

I also second Greg's concerns.
