### ISSUE TITLE
Doc or paper about `field_impl.h`

### ISSUE THREAD

**Issue by bosskwei** [bitcoin-core/secp256k1#615]
Hi guys,
I am a beginner and want to have more understand about the project, but code is really advanced and tricky, is there any doc or paper about how such as `secp256k1_fe_mul_inner()` and `secp256k1_fe_sqr_inner()` are implemented? Why these magic code could work?
Thanks

**Comment by gmaxwell** [comment]
For me, I often find that reading code and taking the time to work through it an expirement is the best way to understand something. a paper has to be _really good_ for it to clearly express complex ideas to someone who isn't already deeply seeped in the subject, and many papers aren't.  Though I pinged other contributors to see if they have suggestions.

Probably the most important non-trivial in this code is the use of an over-complete representation for carry reduction.  Imagine writing out "long multiplication" by hand like you were (probably) taught in school.  You spend a significant amount of time propagating carries between digits. The same is true for the computer (often more so, because conditional behaviour creates dependencies that blocks the CPUs internal parallelism).  But imagine that your digits in your base-10 multiply were allowed to go larger than 9? Then you could defer some carrying operations and perform them all at once.  The limit on this is that your individual operations need to be able to handle the larger digits, so there is a trade-off.

I guess the other important concept is that multiplication (or squaring) is itself an operation which is suitable for algebraic optimization. Although we don't use karatsuba there are many good writeups about how it works online ( such as https://en.wikipedia.org/wiki/Karatsuba_algorithm ) which might help give you a feel for non-trivial multiplication algorithms and help you think of multiplication more as an algorithm and less of a black box.

**Comment by bosskwei** [comment]
Thanks @gmaxwell , your answer is very helpful. I'll close the issue in a few days and wait for someone else with same questions as me.

**Comment by jonasnick** [comment]
A good introduction into finite field arithmetic is this slide deck: https://cryptojedi.org/peter/data/pairing-20131122.pdf

**Comment by bosskwei** [comment]
@jonasnick Thanks, that's exactly what I need.
