### ISSUE TITLE
Multiplying a point by zero

### ISSUE THREAD

**Issue by elichai** [bitcoin-core/secp256k1#616]
Hi,
Shouldn't multiplying a point by zero return the identity element(the point at infinity)
Right now it returns 0 (signifying an error)
https://github.com/bitcoin-core/secp256k1/blob/84a808598b3aa70847d73a0ce43f7893e302fd90/src/eckey_impl.h#L89

**Comment by sipa** [comment]
You can't return such a point.

**Comment by elichai** [comment]
Why can't the point at infinity be a valid public key? 

And I guess all this library is written to operate over public and private keys and not points and field elements, right?

**Comment by sipa** [comment]
@elichai Because you can't serialize it.

**Comment by gmaxwell** [comment]
And also because this library (at least it's public interface) is not a collection of tools for people to roll their own cryptosystems.

I am of the view that any cryptographically library should offer interfaces to non-cryptograhers which are as intrinsically safe as is reasonable possible and bare primitives don't have this property. If there were some protocol that required serializing the point at infinity (which would be a pretty weird requirement) that protocol would include its own serialization that could handle it.
