### ISSUE TITLE
secp256k1_ecdsa_signature invariant can be violated with DER parsing of overflow r,s

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin-core/secp256k1#721]
I was expecting `secp256k1_ecdsa_signature` to have the following invariant:

* `s` must not be 0
* `r` must not be 0
* `s` must not overflow
* `r` must not overflow

Those conditions are checked when signing. https://github.com/bitcoin-core/secp256k1/blob/96d8ccbd16090551aa003bfa4acd108b0496cb89/src/ecdsa_impl.h#L291-L293 

It is also checked at in the parsing of the compact format https://github.com/bitcoin-core/secp256k1/blob/e541a90ef6461007d9c6a74b9f9a7fb8aa34aaa8/src/modules/recovery/main_impl.h#L38-L58

Or 

https://github.com/bitcoin-core/secp256k1/blob/96d8ccbd16090551aa003bfa4acd108b0496cb89/src/secp256k1.c#L350-L369

However, I found that the invarient is violated if you parse from der with overflow `r` and `s`.
In such case, `r` and `s` are converted to `0`, then a `secp256k1_ecdsa_signature` get created out of it.

https://github.com/bitcoin-core/secp256k1/blob/96d8ccbd16090551aa003bfa4acd108b0496cb89/src/ecdsa_impl.h#L102-L151

Then we happily load it into the object without checking.

https://github.com/bitcoin-core/secp256k1/blob/96d8ccbd16090551aa003bfa4acd108b0496cb89/src/secp256k1.c#L341-L343

I think `secp256k1_ecdsa_signature_parse_der` should return false in case of r or s being 0.
~Or having `secp256k1_der_parse_integer` returning false in case of r or s being overflow.~ (does not solve the case if r and s are actually 0)

**Comment by sipa** [comment]
This is intentional.

Parsing of DER is well-defined, and it cannot just fail because we know that for our specific use case the numbers in it are too large. There is no DER violation in this case, and some applications may behave different behavior for invalid DER vs. invalid signature.

Unfortunately, our secp256k_ecdsa_signature type cannot represent variable length integers, so we need to do something... either returning a special status code, or return a special secp256k1_ecdsa_signature that encodes "overflow".

It just so happens that that special value can just be 0, because we know no such signature is ever valid, so they're functionally indistinguishable.

**Comment by NicolasDorier** [comment]
@sipa I agree there is no DER violation, but I find it strange that everywhere the invariants on r and s not being zero is enforced before creating the `secp256k1_ecdsa_signature` type, only not in this case.

I don't think of any side effect of just checking for zero before `secp256k1_ecdsa_signature_save`. I think stronger invariant is safer.

https://github.com/bitcoin-core/secp256k1/blob/96d8ccbd16090551aa003bfa4acd108b0496cb89/src/secp256k1.c#L334-L348

**Comment by real-or-random** [comment]
This behavior is documented:

https://github.com/bitcoin-core/secp256k1/blob/96d8ccbd16090551aa003bfa4acd108b0496cb89/include/secp256k1.h#L402-L409

**Comment by NicolasDorier** [comment]
Closing this.

I understand this is document and this is on purpose, but I still believe is it a bad decision, as it means we can't enforce the invariant "s and r must be zero" on the `secp256k1_ecdsa_signature` type. This is shame because all the other code paths in this library make sure that s and r are not zero before initializing `secp256k1_ecdsa_signature`.
