### ISSUE TITLE
How to get the recover id (v) of secp256k1_ecdsa_signature

### ISSUE THREAD

**Issue by Bowfish** [bitcoin-core/secp256k1#898]
How can I get the r and s values and the recover id (v) of a secp256k1_ecdsa_signature?

Thank you very much for you help.

**Comment by apoelstra** [comment]
This library does not expose any way to do this. You can obtain r and s by parsing the signature (easiest way is to call `secp256k1_signature_porse

**Comment by rickmark** [comment]
This is very difficult since there are really 3 different signature encodings:

1. Plain (r, s) where r and s are 32 byte big endian integers (64 total bytes)
2. Recoverable (r, s, v) where r and s are 32 byte big endian integers, and v is a single byte used for recovery (65 total bytes)
3. Bitcoin compact signatures which are a version/recovery value, r, and s.  This too is 65 bytes.

Because of this, you can't really disambiguate 2 and 3.  If you KNOW its in format 2 or format 3 you can do this yourself by getting the first or last byte of the compact representation.  The API for compact signatures currently assumes 1 outright.  Even if you know which format the internal representation of the sig is 64 bytes and would need to be modified (i've already corrected the documentation that one should expect it to be sizeof(secp256k1_ecdsa_signature) not 64 exactly)

**Comment by apoelstra** [comment]
There are only two signature encodings supported by this library: DER and compact.

Bitcoin's (deprecated) signmessage functionality takes a compact signature plus a recoveryid and encodes this in some weird 65-byte way by adding 27 to the recid or something like that. This library provides a bare minimum of support for this (having recoverable signatures, gated behind a feature flag, and exposing the recid as an integer with no prescribed encoding) because it's needed to compile Bitcoin Core, which is this library's primary target.

There are many reasons to dislike recoverable signatures and I don't expect this library will ever add additional support for them beyond this.

**Comment by rickmark** [comment]
I think we should support recoverable signatures, but we should do it in a way where R, S, and V are all explicitly specified as primitive values instead of any serialized "representation"

This allows a client to marshal them on their own because the client would have more knowledge than the library could ever.

This is why there's still tons of value in ECC functions taking primitive values, because its already been shown that there is variation in the serializing and encoding of these values.  I can re-work a patch-set / API to correctly take values in un-serialized form as well as a native implementation of key recovery (IIRC key recovery requires a value between 1-4 to know which of the four points +/- and P/P') to use for the computation of the ephemeral point for recovering the original signing point

**Comment by sipa** [comment]
@rickmark This library is focused on high-level functionality, exposing safe APIs ideally implementing specific protocols. It deliberately does not expose internals because (a) more risk of shooting yourself in the foot (b) they risk creating a dependency on internal representations which may change. There could be a discussion about changes to that, but this issue isn't the place for that.

As far as ECDSA recovery is concerned, I don't see what the outstanding issue to be addressed is here. The recovery module supports creating/serializing/deserializing/converting of signatures with recovery id. Recovery for normal ECDSA signatures isn't possible, as you'd need to guess the recid. I don't expect that we'll want to expand functionality around that.

I'm going to close this due to unclarity about actionable improvements, but feel free to comment if you believe I missed something here.

**Comment by rickmark** [comment]
I think the only actionable thing is to better document the recoverable APIs and possibly allow it to parse ASN1 and Bitcoin binary representations
