### ISSUE TITLE
Security Vulnerability - null pointer dereference

### ISSUE THREAD

**Issue by darkverbito** [bitcoin-core/secp256k1#948]
I think there's a null pointer dereference issue here:

https://github.com/bitcoin-core/secp256k1/blob/d644dda5c9dbdecee52d1aa259235510fdc2d4ee/src/java/org/bitcoin/NativeSecp256k1.java#L401

**Comment by real-or-random** [comment]
Yes, the order of the checks should be reversed.

But:
1) I don't see how this is a security vulnerability. It will throw a NullPointerException instead of an AssertFailException but that's per se not a security issue.

2) This code is not in our repo. The Java bindings haven been removed more than a year ago, see https://github.com/bitcoin-core/secp256k1/pull/682. Maybe you want to report this at the repo mentioned there but please don't call it a vulnerability and create unnecessary attention.

**Comment by darkverbito** [comment]
Thanks for the update!
